# Generated by Django 2.1.3 on 2018-11-26 16:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id_game', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_wins', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5)),
                ('no_of_lose', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5)),
                ('no_of_draws', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ManyToManyField(related_name='player1', to='profil.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ManyToManyField(related_name='player2', to='profil.Player'),
        ),
    ]
