# Generated by Django 2.1.3 on 2018-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='present',
            field=models.NullBooleanField(default=False),
        ),
    ]
